# -*- coding: utf-8 -*-
"""group_project_eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eULV4Lw5IOPhDl93BcEEgdmPFzUExyUU
"""

import pandas as pd

import numpy as np

import seaborn as sns

# understanding the data

mineplant = pd.read_csv("mineplant.csv")

import csv

with open ("mineplant.csv","r") as csv_file:
  csv_reader=csv.reader(csv_file)

with open("new_mineplant.csv","w") as group_project:
  csv_writer=csv.writer(group_project, delimiter="\t")

mineplant.head()

mineplant.tail()

mineplant.shape

mineplant.describe()

mineplant.columns

# checkimg unique value

mineplant["COMMODITY"].unique()

mineplant["PLANT_MIN"].unique()

mineplant["SITE_NAME"].unique()

mineplant["COMPANY_NA"].unique()

mineplant["STATE_LOCA"].unique()

#cleaning the data

mineplant.isnull().sum()

# there are six variables without a site name; but it might as a result of two sites having thesame longitude or latitude

# normalizing the data

mineplant2 = pd.read_csv("mineplant.csv")

mineplant2.head()

pd.get_dummies(mineplant2["COMMODITY"], drop_first=True)

# relationship analysis between variables by looking at their correlation matrix

corelation = mineplant.corr()

sns.heatmap(corelation, xticklabels=corelation.columns, yticklabels=corelation.columns, annot=True)

# to visualize the relationship between only two variables, we use pairplot.

sns.pairplot(mineplant)

# to further visualize the relationship between variables we use scatter plot.

sns.relplot(x="LONGITUDE", y="LATITUDE", hue="COMMODITY", data=mineplant)

# there is no correlation between the variables, so we investigate further.

sns.relplot(x="LONGITUDE", y="LATITUDE", hue="PLANT_MIN", data=mineplant)

# the scatter plot does not produce any linear relationship, so we look at histogram to understand the shape,
# spread and continuous sample of data.

sns.distplot(mineplant["LATITUDE"])

# we can see that most of the mineplants are within 40km distribution across the country.
# we further investigate this relationship using the scatter plot.
from matplotlib import pyplot as plt

# isolating different variables from the dataframe and comparing them against each other.

mineplant.COMMODITY="ALUMINUM"

mineplant[mineplant.COMMODITY=="ALUMINUM"]

mineplant.COMMODITY="GOLD"

mineplant[mineplant.COMMODITY=="GOLD"]